# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-23 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secret', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Secret',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('secrettext', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('likes', models.ManyToManyField(related_name='secret_liked', to='secret.User')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secret_posted', to='secret.User')),
            ],
        ),
    ]
